import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cn } from "@/sdk/lib/utils";
import { ThemeProvider } from "@/sdk/providers/ThemeProvider";
import { getLocale, getMessages, setRequestLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { Navbar } from "@/components/navbar";
import { SessionProvider } from "next-auth/react";
import { QueryProvider } from "@/sdk/providers/ReactQueryProvider";
import { Toaster } from "@/components/ui/toaster";
import { FirebaseAuthProvider } from "@/sdk/providers/FirebaseAuthProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();

  setRequestLocale(locale);

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={cn(
          "min-h-screen bg-background antialiased",
          geistSans.variable,
          geistMono.variable
        )}
      >
        <QueryProvider>
          <NextIntlClientProvider messages={messages}>
            <SessionProvider>
              <FirebaseAuthProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
                >
                  <SidebarProvider>
                    <main className="min-h-[100dvh] bg-background text-foreground w-full">
                      <Navbar />
                      {children}
                      <Toaster />
                    </main>
                  </SidebarProvider>
                </ThemeProvider>
              </FirebaseAuthProvider>
            </SessionProvider>
          </NextIntlClientProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
